# **Analisis Data dengan Pandas dan NumPy (CPMK M2)**

Materi Pokok:

1.	Struktur data Pandas: Series dan DataFrame

2.	Filtering, grouping, dan aggregation

3.	Operasi array NumPy: slicing, broadcasting, dan universal functions

4.	Penanganan data hilang (missing values)

Nama:Rinaldi Hamzah

NIM:5220411342

Program Studi:Informatika

In [1]:
#Mengakses Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# 2.1 Struktur data Pandas: Series dan DataFrame

Library

In [9]:
#Library
import pandas as pd
import numpy as np

In [8]:
df = pd.read_excel('/content/drive/MyDrive/Semester7 2026/Data Science/pizza_sales_raw.xlsx', header=1)
#semua bentuk karakteristik data bisa di import seperti excel,csv,json
df.head() #melihat 5 baris data pertama

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1.0,1.0,hawaiian_m,1.0,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2.0,2.0,classic_dlx_m,1.0,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3.0,2.0,five_cheese_l,1.0,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4.0,2.0,ital_supr_l,1.0,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5.0,2.0,mexicana_m,1.0,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza

Eksplorasi Data

In [10]:
df.info() #Melihat karakteristik data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  float64
 1   order_id           48620 non-null  float64
 2   pizza_name_id      48620 non-null  object
 3   quantity           48620 non-null  float64
 4   order_date         48620 non-null  object
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  object
 9   pizza_category     48620 non-null  object
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
dtypes: float64(5), object(7)
memory usage: 4.5+ MB

In [16]:
df.columns

Index(['pizza_id', 'order_id', 'pizza_name_id', 'quantity', 'order_date',
       'order_time', 'unit_price', 'total_price', 'pizza_size',
       'pizza_category', 'pizza_ingredients', 'pizza_name'],
      dtype='object')

In [12]:
df.describe() #mendescribsikan bentuk data

           pizza_id      order_id      quantity    unit_price   total_price
count  48620.000000  48620.000000  48620.000000  48620.000000  48620.000000
mean   24310.500000  10701.479761      1.019622     16.494132     16.821474
std    14035.529381   6180.119770      0.143077      3.621789      4.437398
min        1.000000      1.000000      1.000000      9.750000      9.750000
25%    12155.750000   5337.000000      1.000000     12.750000     12.750000
50%    24310.500000  10682.500000      1.000000     16.500000     16.500000
75%    36465.250000  16100.000000      1.000000     20.250000     20.500000
max    48620.000000  21350.000000      4.000000     35.950000     83.000000

In [13]:
df.isnull().sum() #menghitung jumlah data yang hilang
#di dalam data ini ternyata tidak ada missing value

pizza_id             0
order_id             0
pizza_name_id        0
quantity             0
order_date           0
order_time           0
unit_price           0
total_price          0
pizza_size           0
pizza_category       0
pizza_ingredients    0
pizza_name           0
dtype: int64

In [19]:
df.duplicated().sum() #dublikat data
#jika ada maka dihapus
#df = df.drop_duplicates()

np.int64(0)

Cleaning

In [38]:
#mengahpus angka nul
df['pizza_id'] = df['pizza_id'].astype(int)
df['order_id'] = df['order_id'].astype(int)
df['quantity'] = df['quantity'].astype(int)

In [49]:
df['unit_price'] = df['unit_price'].astype(int)
df['total_price'] = df['total_price'].astype(int)

In [46]:
df['order_date'] = pd.to_datetime(
    df['order_date'],
    format='mixed',
    dayfirst=True
)

In [47]:
df['order_time'] = pd.to_datetime(
    df['order_time'],
    format='mixed'
).dt.time

In [40]:
df['pizza_size'] = df['pizza_size'].str.lower().str.strip()
df['pizza_category'] = df['pizza_category'].str.lower().str.strip()
df['pizza_name'] = df['pizza_name'].str.lower().str.strip()
df['pizza_ingredients'] = (
    df['pizza_ingredients']
    .str.lower()
    .str.replace('[^a-z, ]', '', regex=True)
    .str.strip()
)

In [41]:
df['price_check'] = df['quantity'] * df['unit_price']

(df['price_check'] == df['total_price']).value_counts()

True    48620
Name: count, dtype: int64

In [50]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  int64
 1   order_id           48620 non-null  int64
 2   pizza_name_id      48620 non-null  object
 3   quantity           48620 non-null  int64
 4   order_date         48620 non-null  datetime64[ns]
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  int64
 7   total_price        48620 non-null  int64
 8   pizza_size         48620 non-null  object
 9   pizza_category     48620 non-null  object
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
 12  price_check        48620 non-null  int64
dtypes: datetime64[ns](1), int64(6), object(6)
memory usage: 4.8+ MB

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,price_check
0,1,1,hawaiian_m,1,2015-01-01,11:38:36,13,13,m,classic,"sliced ham, pineapple, mozzarella cheese",the hawaiian pizza,13
1,2,2,classic_dlx_m,1,2015-01-01,11:57:40,16,16,m,classic,"pepperoni, mushrooms, red onions, red peppers,...",the classic deluxe pizza,16
2,3,2,five_cheese_l,1,2015-01-01,11:57:40,18,18,l,veggie,"mozzarella cheese, provolone cheese, smoked go...",the five cheese pizza,18
3,4,2,ital_supr_l,1,2015-01-01,11:57:40,20,20,l,supreme,"calabrese salami, capocollo, tomatoes, red oni...",the italian supreme pizza,20
4,5,2,mexicana_m,1,2015-01-01,11:57:40,16,16,m,veggie,"tomatoes, red peppers, jalapeno peppers, red o...",the mexicana pizza,16

# 2.2 Filtering, grouping, dan aggregation

FILTERING

In [51]:
#filter berdasarkan ukuran pizza l
df_l = df[df['pizza_size'] == 'l']
df_l.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,price_check
2,3,2,five_cheese_l,1,2015-01-01,11:57:40,18,18,l,veggie,"mozzarella cheese, provolone cheese, smoked go...",the five cheese pizza,18
3,4,2,ital_supr_l,1,2015-01-01,11:57:40,20,20,l,supreme,"calabrese salami, capocollo, tomatoes, red oni...",the italian supreme pizza,20
5,6,2,thai_ckn_l,1,2015-01-01,11:57:40,20,20,l,chicken,"chicken, pineapple, tomatoes, red peppers, tha...",the thai chicken pizza,20
7,8,3,prsc_argla_l,1,2015-01-01,12:12:28,20,20,l,supreme,"prosciutto di san daniele, arugula, mozzarella...",the prosciutto and arugula pizza,20
16,17,9,ital_cpcllo_l,1,2015-01-01,12:52:01,20,20,l,classic,"capocollo, red peppers, tomatoes, goat cheese,...",the italian capocollo pizza,20

In [55]:
#filter penjualan berdasarkan tahun
df_2015 = df[df['order_date'].dt.year == 2015]
df_2015.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,price_check
0,1,1,hawaiian_m,1,2015-01-01,11:38:36,13,13,m,classic,"sliced ham, pineapple, mozzarella cheese",the hawaiian pizza,13
1,2,2,classic_dlx_m,1,2015-01-01,11:57:40,16,16,m,classic,"pepperoni, mushrooms, red onions, red peppers,...",the classic deluxe pizza,16
2,3,2,five_cheese_l,1,2015-01-01,11:57:40,18,18,l,veggie,"mozzarella cheese, provolone cheese, smoked go...",the five cheese pizza,18
3,4,2,ital_supr_l,1,2015-01-01,11:57:40,20,20,l,supreme,"calabrese salami, capocollo, tomatoes, red oni...",the italian supreme pizza,20
4,5,2,mexicana_m,1,2015-01-01,11:57:40,16,16,m,veggie,"tomatoes, red peppers, jalapeno peppers, red o...",the mexicana pizza,16

In [58]:
#Filter pizza kategori
df_classic = df[df['pizza_category'] == 'classic']
df_classic.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,price_check
0,1,1,hawaiian_m,1,2015-01-01,11:38:36,13,13,m,classic,"sliced ham, pineapple, mozzarella cheese",the hawaiian pizza,13
1,2,2,classic_dlx_m,1,2015-01-01,11:57:40,16,16,m,classic,"pepperoni, mushrooms, red onions, red peppers,...",the classic deluxe pizza,16
11,12,6,the_greek_s,1,2015-01-01,12:29:36,12,12,s,classic,"kalamata olives, feta cheese, tomatoes, garlic...",the greek pizza,12
14,15,9,classic_dlx_s,1,2015-01-01,12:52:01,12,12,s,classic,"pepperoni, mushrooms, red onions, red peppers,...",the classic deluxe pizza,12
16,17,9,ital_cpcllo_l,1,2015-01-01,12:52:01,20,20,l,classic,"capocollo, red peppers, tomatoes, goat cheese,...",the italian capocollo pizza,20

In [62]:
#Filter transaksi dengan quantity
df_qty = df[df['quantity'] > 3]
df_qty.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,price_check
11976,11977,5264,big_meat_s,4,2015-03-30,13:24:35,12,48,s,classic,"bacon, pepperoni, italian sausage, chorizo sau...",the big meat pizza,48
18875,18876,8286,big_meat_s,4,2015-05-19,12:42:46,12,48,s,classic,"bacon, pepperoni, italian sausage, chorizo sau...",the big meat pizza,48
35496,35497,15674,cali_ckn_l,4,2015-09-19,14:16:35,20,83,l,chicken,"chicken, artichoke, spinach, garlic, jalapeno ...",the california chicken pizza,83

GROUPING (Pengelompokan Data)

In [63]:
#Total revenue per kategori pizza
revenue_category = df.groupby('pizza_category')['total_price'].sum()
revenue_category

pizza_category
chicken    187867
classic    216159
supreme    202078
veggie     189716
Name: total_price, dtype: int64

In [64]:
#Total jumlah pizza terjual per ukuran
quantity_size = df.groupby('pizza_size')['quantity'].sum()
quantity_size

pizza_size
l      18956
m      15635
s      14403
xl       552
xxl       28
Name: quantity, dtype: int64

In [65]:
#Jumlah order per tanggal
orders_per_day = df.groupby('order_date')['order_id'].nunique()
orders_per_day

order_date
2015-01-01    69
2015-01-02    67
2015-01-03    66
2015-01-04    52
2015-01-05    54
              ..
2015-12-27    35
2015-12-28    39
2015-12-29    27
2015-12-30    32
2015-12-31    73
Name: order_id, Length: 358, dtype: int64

In [66]:
#Penjualan per jam
df['hour'] = pd.to_datetime(df['order_time'].astype(str)).dt.hour

sales_by_hour = df.groupby('hour')['quantity'].sum()
sales_by_hour

/tmp/ipython-input-790906793.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['hour'] = pd.to_datetime(df['order_time'].astype(str)).dt.hour

hour
9        4
10      18
11    2728
12    6776
13    6413
14    3613
15    3216
16    4239
17    5211
18    5417
19    4406
20    3534
21    2545
22    1386
23      68
Name: quantity, dtype: int64

In [76]:
#Jam dengan penjualan tertinggi
peak_hour = sales_by_hour.idxmax()
peak_value = sales_by_hour.max()
peak_hour, peak_value

(np.int32(12), 6776)

AGGREGATION (Agregasi Statistik)

In [69]:
#Agregasi lengkap per kategori
summary_category = df.groupby('pizza_category').agg(
    total_revenue=('total_price', 'sum'),
    total_quantity=('quantity', 'sum'),
    avg_unit_price=('unit_price', 'mean'),
    total_orders=('order_id', 'nunique')
)
summary_category

                total_revenue  total_quantity  avg_unit_price  total_orders
pizza_category
chicken                187867           11050       16.959408          8536
classic                216159           14888       14.527128         10859
supreme                202078           11987       16.840282          9085
veggie                 189716           11649       16.263342          8941

In [70]:
#Top 5 pizza paling laku
top_5_pizza = (
    df.groupby('pizza_name')['quantity']
    .sum()
    .sort_values(ascending=False)
    .head(5)
)
top_5_pizza

pizza_name
the classic deluxe pizza      2453
the barbecue chicken pizza    2432
the hawaiian pizza            2422
the pepperoni pizza           2418
the thai chicken pizza        2371
Name: quantity, dtype: int64

In [74]:
#Best Seller Berdasarkan Revenue
best_revenue = (
    df.groupby('pizza_name')['total_price']
    .sum()
    .sort_values(ascending=False)
    .head(5)
)
best_revenue

pizza_name
the thai chicken pizza          41712
the barbecue chicken pizza      41004
the california chicken pizza    39700
the classic deluxe pizza        37946
the spicy italian pizza         33628
Name: total_price, dtype: int64

In [71]:
#Average Order Value (AOV)
aov = df.groupby('order_id')['total_price'].sum().mean()
aov

np.float64(37.274941451990635)

# 2.3 Operasi array NumPy: slicing, broadcasting, dan universal functions

SLICING (Memotong Data)

In [77]:
# ambil kolom numerik penting
pizza_array = df[['quantity', 'unit_price', 'total_price', 'pizza_id', 'order_id']].to_numpy()

pizza_array[:5]

array([[ 1, 13, 13,  1,  1],
       [ 1, 16, 16,  2,  2],
       [ 1, 18, 18,  3,  2],
       [ 1, 20, 20,  4,  2],
       [ 1, 16, 16,  5,  2]])

In [78]:
#Ambil hanya kolom quantity
qty = pizza_array[:, 0]
qty[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [80]:
#Ambil unit_price & total_price
price = pizza_array[:, 1:3]
price[:10]

array([[13, 13],
       [16, 16],
       [18, 18],
       [20, 20],
       [16, 16],
       [20, 20],
       [16, 16],
       [20, 20],
       [16, 16],
       [16, 16]])

BROADCASTING (Operasi Massal)

In [81]:
#Simulasi kenaikan harga 10%
unit_price = pizza_array[:, 1] * 1.10
unit_price[:5]

array([14.3, 17.6, 19.8, 22. , 17.6])

In [82]:
#Hitung ulang total_price setelah kenaikan harga
total_price = pizza_array[:, 0] * unit_price
total_price[:5]

array([14.3, 17.6, 19.8, 22. , 17.6])

UNIVERSAL FUNCTIONS (ufuncs)

In [86]:
#Statistik dasar
np.mean(qty), np.median(qty), np.std(qty), np.min(qty), np.max(qty)

(np.float64(1.0196215549156726),
 np.float64(1.0),
 np.float64(0.1430755379369698),
 np.int64(1),
 np.int64(4))

In [87]:
#Operasi matematika
np.sqrt(pizza_array[:, 2])   # akar dari total_price
np.log(pizza_array[:, 2] + 1)

array([2.63905733, 2.83321334, 2.94443898, ..., 2.56494936, 3.04452244,
       2.56494936])

In [88]:
#Operasi logika
pizza_array[:, 2] > 50

array([False, False, False, ..., False, False, False])

In [89]:
#Transaksi besar (quantity ≥ 3)
large_order = pizza_array[pizza_array[:, 0] >= 3]
large_order[:5]

array([[   3,   20,   62,  184,   78],
       [   3,   16,   50,  342,  144],
       [   3,   12,   37,  903,  394],
       [   3,   16,   48, 5895, 2612],
       [   3,   16,   48, 7105, 3136]])

In [90]:
#Rata-rata total_price transaksi besar
np.mean(large_order[:, 2])

np.float64(49.5)

# 2.4 Penanganan data hilang (missing values)

In [91]:
df.isna().sum()

pizza_id             0
order_id             0
pizza_name_id        0
quantity             0
order_date           0
order_time           0
unit_price           0
total_price          0
pizza_size           0
pizza_category       0
pizza_ingredients    0
pizza_name           0
price_check          0
hour                 0
dtype: int64

In [92]:
#menghapus tabel
df = df.dropna(subset=['price_check'])

In [94]:
#Kolom Numerik Transaksi
df['quantity'].fillna(1, inplace=True)

/tmp/ipython-input-2855449050.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['quantity'].fillna(1, inplace=True)

In [95]:
df['unit_price'] = df.groupby('pizza_name_id')['unit_price']\
                      .transform(lambda x: x.fillna(x.mean()))

In [96]:
df['total_price'] = df['quantity'] * df['unit_price']

In [97]:
df['pizza_size'].fillna(df['pizza_size'].mode()[0], inplace=True)
df['pizza_category'].fillna(df['pizza_category'].mode()[0], inplace=True)

/tmp/ipython-input-2639469859.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['pizza_size'].fillna(df['pizza_size'].mode()[0], inplace=True)
/tmp/ipython-input-2639469859.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['pizza_category'].fillna(df['pizza_category'].mode()[0], inplace=True)

In [98]:
#Kolom Teks
df['pizza_ingredients'].fillna('Unknown', inplace=True)
df['pizza_name'].fillna('Unknown', inplace=True)

/tmp/ipython-input-15815753.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['pizza_ingredients'].fillna('Unknown', inplace=True)
/tmp/ipython-input-15815753.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['pizza_name'].fillna('Unknown', inplace=True)

In [102]:
df

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,price_check,hour
0,1,1,hawaiian_m,1,2015-01-01,11:38:36,13,13,m,classic,"sliced ham, pineapple, mozzarella cheese",the hawaiian pizza,13,11
1,2,2,classic_dlx_m,1,2015-01-01,11:57:40,16,16,m,classic,"pepperoni, mushrooms, red onions, red peppers,...",the classic deluxe pizza,16,11
2,3,2,five_cheese_l,1,2015-01-01,11:57:40,18,18,l,veggie,"mozzarella cheese, provolone cheese, smoked go...",the five cheese pizza,18,11
3,4,2,ital_supr_l,1,2015-01-01,11:57:40,20,20,l,supreme,"calabrese salami, capocollo, tomatoes, red oni...",the italian supreme pizza,20,11
4,5,2,mexicana_m,1,2015-01-01,11:57:40,16,16,m,veggie,"tomatoes, red peppers, jalapeno peppers, red o...",the mexicana pizza,16,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,2015-12-31,21:23:10,16,16,m,chicken,"chicken, red onions, red peppers, mushrooms, a...",the chicken alfredo pizza,16,21
48616,48617,21348,four_cheese_l,1,2015-12-31,21:23:10,17,17,l,veggie,"ricotta cheese, gorgonzola piccante cheese, mo...",the four cheese pizza,17,21
48617,48618,21348,napolitana_s,1,2015-12-31,21:23:10,12,12,s,classic,"tomatoes, anchovies, green olives, red onions,...",the napolitana pizza,12,21
48618,48619,21349,mexicana_l,1,2015-12-31,22:09:54,20,20,l,veggie,"tomatoes, red peppers, jalapeno peppers, red o...",the mexicana pizza,20,22
48619,48620,21350,bbq_ckn_s,1,2015-12-31,23:02:05,12,12,s,chicken,"barbecued chicken, red peppers, green peppers,...",the barbecue chicken pizza,12,23

# Tugas Praktikum

1.	Analisis dataset Pizza Sales untuk menentukan jenis dengan jumlah penjualan tertinggi dan tren harian penjualan.

In [103]:
#Jenis Pizza dengan Penjualan Tertinggi
top_quantity = (
    df.groupby('pizza_name')['quantity']
      .sum()
      .sort_values(ascending=False)
      .head(10)
)
print(top_quantity)

pizza_name
the classic deluxe pizza        2453
the barbecue chicken pizza      2432
the hawaiian pizza              2422
the pepperoni pizza             2418
the thai chicken pizza          2371
the california chicken pizza    2370
the sicilian pizza              1938
the spicy italian pizza         1924
the southwest chicken pizza     1917
the big meat pizza              1914
Name: quantity, dtype: int64

In [104]:
#Berdasarkan Total Pendapatan
top_revenue = (
    df.groupby('pizza_name')['total_price']
      .sum()
      .sort_values(ascending=False)
      .head(10)
)
print(top_revenue)

pizza_name
the thai chicken pizza          41656
the barbecue chicken pizza      40944
the california chicken pizza    39632
the classic deluxe pizza        37944
the spicy italian pizza         33592
the southwest chicken pizza     33268
the italian supreme pizza       32348
the hawaiian pizza              31183
the four cheese pizza           30576
the sicilian pizza              30456
Name: total_price, dtype: int64

In [105]:
#Tren Penjualan Harian
daily_sales = (
    df.groupby('order_date')['total_price']
      .sum()
      .reset_index()
)

In [106]:
daily_sales['day_name'] = daily_sales['order_date'].dt.day_name()

In [107]:
#Rata-rata Penjualan per Hari
day_trend = (
    daily_sales.groupby('day_name')['total_price']
      .mean()
      .reindex([
          'Monday','Tuesday','Wednesday',
          'Thursday','Friday','Saturday','Sunday'
      ])
)

print(day_trend)

day_name
Monday       2173.937500
Tuesday      2134.307692
Wednesday    2138.711538
Thursday     2309.961538
Friday       2645.900000
Saturday     2303.461538
Sunday       1855.019231
Name: total_price, dtype: float64

2.	Lakukan normalisasi terhadap kolom numerik menggunakan NumPy.

In [108]:
#Implementasi dengan NumPy
# Pilih kolom numerik
numerical_cols = ['quantity', 'unit_price', 'total_price']

# Salin data agar aman
df_norm = df.copy()

for col in numerical_cols:
    col_min = np.min(df[col])
    col_max = np.max(df[col])

    df_norm[col] = (df[col] - col_min) / (col_max - col_min)

In [109]:
df_norm[numerical_cols].head()

   quantity  unit_price  total_price
0       0.0    0.153846     0.056338
1       0.0    0.269231     0.098592
2       0.0    0.346154     0.126761
3       0.0    0.423077     0.154930
4       0.0    0.269231     0.098592

In [110]:
for col in numerical_cols:
    mean = np.mean(df[col])
    std = np.std(df[col])

    df_norm[col] = (df[col] - mean) / std

In [112]:
df_norm.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,price_check,hour
0,1,1,hawaiian_m,-0.137141,2015-01-01,11:38:36,-0.864264,-0.779412,m,classic,"sliced ham, pineapple, mozzarella cheese",the hawaiian pizza,13,11
1,2,2,classic_dlx_m,-0.137141,2015-01-01,11:57:40,-0.010616,-0.082556,m,classic,"pepperoni, mushrooms, red onions, red peppers,...",the classic deluxe pizza,16,11
2,3,2,five_cheese_l,-0.137141,2015-01-01,11:57:40,0.558482,0.382014,l,veggie,"mozzarella cheese, provolone cheese, smoked go...",the five cheese pizza,18,11
3,4,2,ital_supr_l,-0.137141,2015-01-01,11:57:40,1.127580,0.846584,l,supreme,"calabrese salami, capocollo, tomatoes, red oni...",the italian supreme pizza,20,11
4,5,2,mexicana_m,-0.137141,2015-01-01,11:57:40,-0.010616,-0.082556,m,veggie,"tomatoes, red peppers, jalapeno peppers, red o...",the mexicana pizza,16,11